### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by ArthurSav**
Updates iOS requirements

### CODE REVIEW

**Comment by axelniklasson** [comment]
@ArthurSav I actually don't remember the latest status on the iOS app files -- do we support both .app files and zips? Checking our [docs](https://docs.mobile.dev/getting-started/uploading-flows-from-ci) I see we say:

> On iOS, point to the *.app simulator build directory.

which is a bit unclear to me but I assume that this means the `.zip`

**Comment by ArthurSav** [comment]
It should support both inputs

**Comment by axelniklasson** [comment]
> It should support both inputs

Gotcha! Can you ensure that this is clearly spelled out so users are not confused? We want to be consistent with our instructions across our different documentation surfaces so if we say `.zip` or `.app` file here I think it should be the same in our docs.

**Review by axelniklasson — APPROVED** [review]

**Comment by ArthurSav** [comment]
Updated the docs with the following

Screenshot 2022-10-28 at 13 01 49

**Pull request merged**
